import { env } from 'cloudflare:workers';

export function getRuntimeBindings(): Cloudflare.Env {
  return {
    DB: env.DB,
    ACCESS_MODE: env.ACCESS_MODE ?? process.env.ACCESS_MODE,
    APP_ORIGIN: env.APP_ORIGIN ?? process.env.APP_ORIGIN,
    APP_AUTHOR_MODE: env.APP_AUTHOR_MODE ?? process.env.APP_AUTHOR_MODE,
    APP_AUTHOR_EMAILS: env.APP_AUTHOR_EMAILS ?? process.env.APP_AUTHOR_EMAILS,
    APP_OWNER_EMAIL: env.APP_OWNER_EMAIL ?? process.env.APP_OWNER_EMAIL,
    APP_OWNER_NAME: env.APP_OWNER_NAME ?? process.env.APP_OWNER_NAME,
    RESEND_API_KEY: env.RESEND_API_KEY ?? process.env.RESEND_API_KEY,
    MAIL_FROM: env.MAIL_FROM ?? process.env.MAIL_FROM,
    NOTIFICATION_DRAIN_LIMIT:
      env.NOTIFICATION_DRAIN_LIMIT ?? process.env.NOTIFICATION_DRAIN_LIMIT,
    NOTIFICATION_DRAIN_INTERVAL_MS:
      env.NOTIFICATION_DRAIN_INTERVAL_MS ??
      process.env.NOTIFICATION_DRAIN_INTERVAL_MS,
    NOTIFICATION_LEASE_SECONDS:
      env.NOTIFICATION_LEASE_SECONDS ?? process.env.NOTIFICATION_LEASE_SECONDS,
    NOTIFICATION_RETRY_BASE_SECONDS:
      env.NOTIFICATION_RETRY_BASE_SECONDS ??
      process.env.NOTIFICATION_RETRY_BASE_SECONDS,
    MAX_OWNED_DOCUMENTS:
      env.MAX_OWNED_DOCUMENTS ?? process.env.MAX_OWNED_DOCUMENTS,
    MAX_COMMENTS_PER_DOCUMENT:
      env.MAX_COMMENTS_PER_DOCUMENT ?? process.env.MAX_COMMENTS_PER_DOCUMENT,
    MAX_ACTIVE_SHARES_PER_DOCUMENT:
      env.MAX_ACTIVE_SHARES_PER_DOCUMENT ??
      process.env.MAX_ACTIVE_SHARES_PER_DOCUMENT,
    MAX_REVISIONS_PER_DOCUMENT:
      env.MAX_REVISIONS_PER_DOCUMENT ?? process.env.MAX_REVISIONS_PER_DOCUMENT,
  };
}
